name: Build docker image

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: version
        run: |
          version=$(git tag --points-at HEAD)
          prev_version=$(git describe --abbrev=0 --tags --exclude="$(git describe --abbrev=0 --tags)")
          echo "version=$version" >> "$GITHUB_OUTPUT"
          echo "prev_version=$prev_version" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/hex-developer/oidc-provider:${{ steps.version.outputs.version }}
          cache-from: type=registry,ref=ghcr.io/hex-developer/oidc-provider:${{ steps.version.outputs.prev_version }}
          cache-to: type=inline
